---
# tasks file for ansible-ansible
- name: Install ansible dependencies
  apt:
    name={{item}}
    state=installed
    update_cache=yes
  with_items:
       - software-properties-common
       - python-pycurl
- name: Add ansible PPA repository
  apt_repository:
    repo: ppa:ansible/ansible
    state: present
- name: Install ansible
  apt: name={{item}} state=latest update_cache=yes
  with_items:
       - ansible
